### PR TITLE
Adding attributes to enable printing the MOTD.

### PR DESCRIPTION
**Pull request by dmerrick**
We like having a MOTD, so I added these attributes to enable support for that.

### CODE REVIEW

**Comment by dmerrick** [comment]
Not sure why it failed the specs. Let me know if I can do anything to improve it!

**Comment by chris-rock** [comment]
@dmerrick great work. Thanks for adding these options. One small improvement would be to add some test to ChefSpec: https://github.com/TelekomLabs/chef-ssh-hardening/blob/master/spec/recipes/server_spec.rb

I will have a look into the travis issues.

**Comment by chris-rock** [comment]
@dmerrick could you rebase please? we fixed the tests in travis. Therefore everything should work now.

**Comment by chris-rock** [comment]
@dmerrick Thank you very much!

**Pull request merged**
